version: 0.0.{build}

branches:
  except:
    - l10n_master # Crowdin
    - gh-pages # Website

image: Visual Studio 2019

configuration:
- Debug
- Release

# Used in build.cake
environment:
  imgur_client_id:
    secure: Y/2WUSisk7oLSQNY1YzUxw==
  yt_client_id:
    secure: CPwUWOhTyZ2IiE+lvVilTKQz1h8sbn7FmkTJvtTlY6mJf2pDlfDhFmhDk1i47M9OPnD4y8a8BlB6yfkpVt/0U/PODAXPzFR0QuOWIfJvltc=
  yt_client_secret:
    secure: fsl/BRldjlmEJCroWa0iqw5tAxbGx84BbHT3BpzaeX4=
  choco_key:
    secure: h5jOVeiDmjLnF3EotkOhBFJharX/9TWx6OWykiXn30pWSIfVjSvAaCJM1Y48zjXr
  git_key:
    secure: eRA1NCG/iXaLTQaBbe2X5Tpje+2Hvk3WOPEP3ZLPFMqW7ZS0ZMTb4UXpw7w59pbc

install:
  - dotnet tool install -g Cake.Tool --version 0.32.1
  - choco install innosetup -y --no-progress

# Build using Cake
build_script:
  - ps: >-
      $tag = $env:APPVEYOR_REPO_TAG_NAME

      if ($tag -ne $null)
      {
        $env:prerelease = $tag.Contains("-")

        if ($tag -match "^build-number-")
        {
          Write-Host "Build number tag is skipped"
          Exit-AppveyorBuild
        }
        else 
        {
          dotnet-cake --target=CI --configuration=$env:CONFIGURATION --build_version=$tag
        }
      }
      else
      {
        $version = "v0.0." + $env:APPVEYOR_BUILD_NUMBER

        dotnet-cake --target=CI --configuration=$env:CONFIGURATION --build_version=$version
      }

test: off

artifacts:
  - path: temp/Captura-Portable.zip
    name: Portable
  - path: temp/Captura-Setup.exe
    name: Setup
  - path: temp/captura.*.nupkg
    name: Chocolatey

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: Captura $(APPVEYOR_REPO_TAG_NAME)
    prerelease: $(prerelease)
    description: "[Changelog](https://github.com/MathewSachin/Captura/tree/master/docs/Changelogs)"
    auth_token: $(git_key)
    artifact: Portable, Setup
    on:
      configuration: Release
      appveyor_repo_tag: true

  - provider: NuGet
    server: https://chocolatey.org
    api_key: $(choco_key)
    artifact: Chocolatey
    on:
      configuration: Release
      appveyor_repo_tag: true