version: 2.0.{build}

image: Visual Studio 2017

install:
  # Update Submodules
  - git submodule init
  - git submodule update

  # Restore packages
  - nuget restore src/Captura.sln

build:
  project: src\Captura.sln